### ISSUE TITLE
Failed to register event.

### ISSUE THREAD

**Issue by metalshark** [Browsit/BossQuestsModule#2]
I am using Boss 3.6.4 and Quests 3.8.5 with Boss Quests Module 1.0 on Paper #90 (Minecraft 1.15.2)

The console is reporting the following:

`[14:05:47 ERROR]: [Quests] Plugin Quests v3.8.5-b64 has failed to register events for class me.pikamug.BossQuestsModule.BossKillObjective because org/mineacademy/boss/api/event/BossDeathEvent does not exist.`

**Comment by PikaMug** [comment]
Thanks for the report. It looks like Boss is missing its API package as of version 3.6.2, so downgrading to 3.6.1 is the temporary fix. I've reached out to the developer, so hopefully the next release of Boss will resolve the issue.

**Comment by lackoSK** [comment]
Hello,

Can you try to update your Boss to the latest version (3.6.4) and see if it still happens to you? 

Regards,
lackoSK | Mineacademy Support

**Comment by metalshark** [comment]
I was using 3.6.4.

**Comment by metalshark** [comment]
Fixed in 3.6.5 of Boss.

Thank you for helping!

**Comment by skerit** [comment]
Just FYI: I'm using Boss 3.6.7 but I still get the error:

`Plugin Quests v3.8.4-b56 has failed to register events for class me.pikamug.BossQuestsModule.BossKillObjective because org/mineacademy/boss/api/event/BossDeathEvent does not exist.`

Guess I'll downgrade to 3.6.1 for now

**Comment by PikaMug** [comment]
Boss 3.6.5 restored the /api package, but now the /api/event package is missing as of the 3.6.6 version. Perhaps @lackoSK could assist further?

For now, use only Boss 3.6.1 or 3.6.5.

**Comment by skerit** [comment]
Oh good to know 3.6.5 actually does work, I'll upgrade to that at least. Thanks.

I also made an issue on their repository:
https://github.com/kangarko/Boss/issues/512
